added team members names
Lambda-School-Labs/Labs26-Bridgegood-FE pull request #48
Opened 2020-10-01 17:22 UTC by acarrillo3

# Description

Making the ReadMe our Teams

## Type of change
- [ ] Documentation Change

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed and commented by at least two peers
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-10-01 19:11 UTC, DrakeAlia approved these changes

2020-10-01 23:22 UTC, Gregory-Hawman submitted a review, later dismissed

2020-10-02 00:14 UTC, antonyk requested changes
I think the table is buggy (previewed it by switching to the branch)

2020-10-02 23:31 UTC, antonyk commented on README.md
> +You can find the deployed project at [bridgegood.dev](http://main.d2pjupszhlnsi0.amplifyapp.com/login).
the url should be https://bridgegood.dev

2020-10-02 23:34 UTC, antonyk commented on README.md
> +#### Front end deployed to `Amazon AWS` built using:
change 'Amazon AWS' to 'AWS Amplify'

2020-10-03 00:00 UTC, DrakeAlia submitted a review, later dismissed

2020-10-04 16:58 UTC, merged